### PR TITLE
fr messages.po

### PR DESCRIPTION
**Pull request by serpico**
several strings added

### CODE REVIEW

**Comment by serpico** [comment]
@minimalparts I've been wondering, line 728 to 732 from my PR `#: app/templates/search/results.html:43` already appears in French in the UI, although not translated yet in messages.po

I guess it must comes from somewhere else...

**Comment by minimalparts** [comment]
@serpico I had made a few additional changes on the test instance itself when I solved the issue with the captcha. I think you can just make your changes as you see fit and I will add one more commit at the end to smooth things over. Thank you!

**Comment by minimalparts** [comment]
@serpico small question: had you re-run flask-babel on your installation? Just wondering why we also have a new German file :D (Which is good, btw, but I'm trying to figure out what happened.)

**Comment by serpico** [comment]
> @serpico I had made a few additional changes on the test instance itself when I solved the issue with the captcha. I think you can just make your changes as you see fit and I will add one more commit at the end to smooth things over. Thank you!

I picked up your version as is and pasted it in my soon-to-be-pushed PR

**Comment by serpico** [comment]
> @serpico small question: had you re-run flask-babel on your installation? Just wondering why we also have a new German file :D (Which is good, btw, but I'm trying to figure out what happened.)

Not that I know, I just sync-ed your 22-translations branch to make sure I have the latest version before making my edits.

**Pull request closed without merging**
